### ISSUE TITLE
[suggestion] Include an example of Great Tables

### ISSUE THREAD

**Issue by garrettgman** [posit-marketing/visit-diagnoses-browser#1]
The two bar graphs are identical. You could have the comorbidity drop down affect the first bar graph, which would free up the real estate consumed by the second bar graph.

That would be a great place to include a table made with Great Tables. Tables complement visualizations and value boxes as methods for displaying data—and we have a great solution to promote with Great Tables.

**Comment by ivelasq** [comment]
Thanks @garrettgman! This Shiny app uses R, but I can use that space to create a table with {gt}.
