### ISSUE TITLE
[suggestion] Telegraph the intended use case for the app

### ISSUE THREAD

**Issue by garrettgman** [posit-marketing/visit-diagnoses-browser#3]
If we use the title and some of the sidebar text to suggest how someone would use the app to solve a real life / in industry problem, it would underscore that Shiny and Connect solve real problems for non-coders.

I'm not sure how I would word that for the app as it exists, but to riff off of #2 , we could title the app:
* Identify disease clusters by population
* Identify common comorbidities by population
* etc.

(p.s. These issue trackers feel so impersonal. I'm sorry if my feedback is coming across as tactless, or going way beyond the scope of feedback you have invited. I don't mean for it to be so!)

**Comment by ivelasq** [comment]
Edited the title 👍 Thanks so much!
